# --- Stable Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-stable
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
      version: stable
  template:
    metadata:
      labels:
        app: react
        version: stable
    spec:
      containers:
        - name: react
          image: react-app:v1
          ports:
            - containerPort: 80

# ---Canary Deployment---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-canary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react
      version: canary
  template:
    metadata:
      labels:
        app: react
        version: canary
    spec:
      containers:
        - name: react
          image: react-app:v2
          ports:
            - containerPort: 80

# --- Service (Selects Both Versions) ---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
   app: react
  ports:
    - port: 80
      targetPort: 80

# --- Canary Ingress (10% Traffic) ---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-canary-ingress
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"  # 10% traffic
spec:
  rules:
    - host: react.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-service
                port:
                  number: 80
